#!/usr/bin/env python3
"""
Generate docs/DEVICES.md -- the full device table as recovered.

Merges three sources so the table shows, per device number, what is actually
known and where it came from:

  * Datalyse.ini          the authoritative device list and ON/OFF state
  * drivers/devices.py    the identification exchange recovered from the binary
  * drivers/catalog.py    which driver implements the measurement, and its
                          provenance (doc / binary / inferred)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datalogger.config import DatalyseConfig, find_file          # noqa: E402
from datalogger.drivers import registry                          # noqa: E402
from datalogger.drivers.devices import DEVICE_PROFILES          # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SOURCE_LABEL = {
    "doc": "**exact**",
    "binary": "identity exact",
    "inferred": "settings only",
}


def main(outpath: str) -> None:
    ini = find_file(os.path.join(ROOT, "original"), "Datalyse.ini")
    if ini is None:
        raise SystemExit("Datalyse.ini not found")
    cfg = DatalyseConfig.load(ini)
    reg = registry()

    exact = ident = settings = placeholder = 0
    lines = [
        "# Device support",
        "",
        "Generated by `scripts/make_device_doc.py`. Do not edit by hand.",
        "",
        "**`driver`** is the key in `datalogger/drivers/catalog.py`.",
        "**`provenance`** says how much of the protocol is actually known:",
        "",
        "| provenance | meaning |",
        "|---|---|",
        "| **exact** | the vendor help documents the whole measurement exchange; "
        "the parser is a transcription |",
        "| identity exact | the identify command and its expected answer were "
        "recovered from `Datalyse.exe`; the measurement query comes from the "
        "instrument's own manual, not from Datalyse |",
        "| settings only | baud/parity/stop/data and the identification strings "
        "are known, the response layout is not — `generic` reads a line and "
        "extracts the numbers |",
        "| n/a | the number is reserved and unused in `Datalyse.ini` |",
        "",
        f"`Datalyse.ini`: `{ini}` — {len(cfg.devices)} device numbers, "
        f"{len(cfg.enabled_devices())} switched ON.",
        "",
        "| # | device | driver | serial | id command | expects | provenance |",
        "|---:|---|---|---|---|---|---|",
    ]

    for number in sorted(cfg.devices):
        prof = DEVICE_PROFILES.get(number)
        dev = cfg.devices[number]
        if prof is None:
            continue
        if prof.serial is None:
            placeholder += 1
            lines.append(f"| {number} | {prof.name} | — | — | — | — | n/a |")
            continue
        drv = prof.driver or "—"
        src = SOURCE_LABEL.get(reg[drv].source, "—") if drv in reg else "—"
        if src == "**exact**":
            exact += 1
        elif src == "identity exact":
            ident += 1
        else:
            settings += 1
        icmd = f"`{prof.id_command}`" if prof.id_command else "*none*"
        exp = ", ".join(f"`{e}`" for e in prof.id_expect) or "—"
        lines.append(f"| {number} | {prof.name} | `{drv}` | "
                     f"{prof.serial.describe()} | {icmd} | {exp} | {src} |")

    lines += [
        "",
        "## Totals",
        "",
        f"* **exact** measurement protocols: {exact}",
        f"* identification recovered, measurement inferred: {ident}",
        f"* serial settings only: {settings}",
        f"* reserved / unused numbers: {placeholder}",
        f"* drivers registered: {len(reg)}",
        "",
        "## Devices Datalyse itself could not identify",
        "",
        "These carry no version exchange in the dispatcher — the original shows "
        "its own message and measures anyway. The messages are preserved in "
        "`drivers/devices.py`.",
        "",
    ]
    for number in sorted(DEVICE_PROFILES):
        p = DEVICE_PROFILES[number]
        if p.id_command is None and p.note and p.driver not in (None,):
            lines.append(f"* **{number} {p.name}** — {p.note}")
    lines.append("")

    with open(outpath, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {outpath}: {exact} exact, {ident} identity-only, "
          f"{settings} settings-only, {placeholder} unused")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "docs/DEVICES.md")
